### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by jurgendn** [amateur3673/ComputerVision#1]
Làm cái github pages đi viết bài cho nó dễ, có gì bọn t vào đọc cũng dễ hơn

**Comment by amateur3673** [comment]
> 
> 
> Làm cái github pages đi viết bài cho nó dễ, có gì bọn t vào đọc cũng dễ hơn

Có nhiều cái vẫn chưa hiểu lắm mà, làm page sai thì hơi ngại.

**Comment by jurgendn** [comment]
Lol bọn này dùng jekyll mà làm nửa tiếng là xong, tải template sẵn về xong config lại 1 tí là được. T với Hiệp cũng có, làm nhanh vc

**Comment by amateur3673** [comment]
> Lol bọn này dùng jekyll mà làm nửa tiếng là xong, tải template sẵn về xong config lại 1 tí là được. T với Hiệp cũng có, làm nhanh vc

Dễ hả. Thế để mấy hôm nx nghiên cứu

**Comment by jurgendn** [comment]
> > Lol bọn này dùng jekyll mà làm nửa tiếng là xong, tải template sẵn về xong config lại 1 tí là được. T với Hiệp cũng có, làm nhanh vc
> 
> Dễ hả. Thế để mấy hôm nx nghiên cứu

https://jekyllthemes.io/jekyll-portfolio-themes

Xem theme ở đây cái nào đẹp thì bốc về xong host lên github luôn. Có gì t vào đọc cho dễ, nhìn nó lại nguy hiểm vl
